######################################################################
#
# File name : fulladder_dataflow_tb_compile.do
# Created on: Fri Feb 07 14:44:20 -0600 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
transcript off
onbreak {quit}
onerror {quit}

transcript on
vlib work

vmap secureip {C:/Users/lucas/Documents/fpga/lab2/Lab2_afterlab/Lab2/lab2_3_1/secureip/secureip.lib}
vmap unimacro_ver {C:/Users/lucas/Documents/fpga/lab2/Lab2_afterlab/Lab2/lab2_3_1/unimacro_ver/unimacro_ver.lib}
vmap unisims_ver {C:/Users/lucas/Documents/fpga/lab2/Lab2_afterlab/Lab2/lab2_3_1/unisims_ver/unisims_ver.lib}
vmap unisim {C:/Users/lucas/Documents/fpga/lab2/Lab2_afterlab/Lab2/lab2_3_1/unisim/unisim.lib}

vlib activehdl/xil_defaultlib

null [set origin_dir "C:/Users/lucas/Documents/fpga/lab2/Lab2_afterlab/Lab2/lab2_3_1/lab2_3_1.sim/sim_1/behav/activehdl"]
null [set vlog_opts {-incr -l xil_defaultlib}]
null [set vcom_opts {-incr}]


vlog -v2k5 {*}$vlog_opts -work xil_defaultlib  \
	"$origin_dir/../../../../lab2_3_1.srcs/sources_1/new/fulladder_dataflow.v" \
	"$origin_dir/../../../../lab2_3_1.srcs/sources_1/imports/fpga/fulladder_dataflow_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "C:/Users/lucas/Documents/fpga/lab2/Lab2_afterlab/Lab2/lab2_3_1/lab2_3_1.sim/sim_1/behav/activehdl/glbl.v"

quit
