######################################################################
#
# File name : lab2_2_1_partA_tb_simulate.do
# Created on: Thu Jan 30 08:38:21 -0600 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
transcript off
opendesign C:/Temp/lucaspeacock/FPGA/Lab2/lab2_2_1/lab2_2_1.sim/sim_1/behav/activehdl/lab2_2_1/lab2_2_1.adf
set SIM_WORKING_FOLDER $dsn/..
asim -asdb +access +r +m+lab2_2_1_partA_tb -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -O5 xil_defaultlib.lab2_2_1_partA_tb xil_defaultlib.glbl

if { ![batch_mode] } {
	wave *
} else {
	log *
}


run 1000ns
if [batch_mode] {
	endsim
	quit
}
