######################################################################
#
# File name : lab2_2_1_partA_tb_compile.do
# Created on: Thu Jan 30 08:38:05 -0600 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
transcript off
onbreak {quit}
onerror {quit}

createdesign {lab2_2_1} {C:/Temp/lucaspeacock/FPGA/Lab2/lab2_2_1/lab2_2_1.sim/sim_1/behav/activehdl}
opendesign {C:/Temp/lucaspeacock/FPGA/Lab2/lab2_2_1/lab2_2_1.sim/sim_1/behav/activehdl/lab2_2_1/lab2_2_1.adf}
vlib work

vlib activehdl/xil_defaultlib
vdel -lib xil_defaultlib -all

null [set origin_dir "C:/Temp/lucaspeacock/FPGA/Lab2/lab2_2_1/lab2_2_1.sim/sim_1/behav/activehdl"]
null [set vlog_opts {}]
null [set vcom_opts {}]


eval vlog -v2k5 $vlog_opts -work xil_defaultlib  \
	"$origin_dir/../../../../lab2_2_1.srcs/sources_1/new/comparator_dataflow.v" \
	"$origin_dir/../../../../lab2_2_1.srcs/sources_1/new/lab2_2_1.v" \
	"$origin_dir/../../../../lab2_2_1.srcs/sources_1/new/lab2_2_1_partA.v" \
	"$origin_dir/../../../../lab2_2_1.srcs/sources_1/imports/new/mux2.v" \
	"$origin_dir/../../../../lab2_2_1.srcs/sources_1/imports/downloads/lab2_2_1_partA_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "C:/Temp/lucaspeacock/FPGA/Lab2/lab2_2_1/lab2_2_1.sim/sim_1/behav/activehdl/glbl.v"

quit
