######################################################################
#
# File name : fulladder_dataflow_tb_compile.do
# Created on: Wed Feb 05 23:21:24 -0600 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
transcript off
onbreak {quit}
onerror {quit}

transcript on
vlib work

vlib activehdl/xil_defaultlib

null [set origin_dir "C:/Users/lucas/Documents/fpga/lab2/Lab2_afterlab/Lab2/test/test.sim/sim_1/behav/activehdl"]
null [set vlog_opts {-incr -l xil_defaultlib}]
null [set vcom_opts {-relax -incr}]


vlog -v2k5 {*}$vlog_opts -work xil_defaultlib  \
	"$origin_dir/../../../../test.srcs/sources_1/imports/fpga/lab2/lab3_1_1/lab3_1_1.srcs/sources_1/new/fulladder_dataflow.v" \
	"$origin_dir/../../../../test.srcs/sources_1/imports/fpga/fulladder_dataflow_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "C:/Users/lucas/Documents/fpga/lab2/Lab2_afterlab/Lab2/test/test.sim/sim_1/behav/activehdl/glbl.v"

quit
